services:
    app:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - public:/var/www/html/public:rw
            - database:/var/www/html/database:rw
        env_file:
            - stack.env
volumes:
    public:
    database:
networks:
    int_proxy:
        external: true
