services:
    app:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - app:/var/www/html:rw
        env_file:
            - .env
volumes:
    app:
